export default {
  height: 500,
  charCounterCount: true,
  toolbarButtons: [
    'bold',
    'italic',
    'underline',
    '|',
    'fontFamily',
    'fontSize',
    'color',
    '|',
    'paragraphFormat',
    'align',
    'formatOL',
    'formatUL',
    'outdent',
    'indent',
    'quote',
    'strikeThrough',
    'subscript',
    'superscript',
    '|',
    'insertLink',
    'insertHR',
    'selectAll',
    'clearFormatting',
    '|',
    'spellChecker',
    'help',
    '|',
    'undo',
    'redo',
  ],
};
